const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http');const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
(async()=>{const server=http.createServer((q,r)=>{r.setHeader('Content-Type','text/html');r.end(fs.readFileSync('dist/index.html'));});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
const args=require(process.env.CHROMIUM_ARGS_MODULE).default.args.filter(a=>a!=='--single-process');browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,args:[...args,'--disable-audio-output'],headless:true});const errors=[];
for(const slots of [2,3]){const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(slots=>{const now=Date.now();window.testNow=now;Date.now=()=>window.testNow;const fish={id:'upgrade-fish',name:'Coral',species:'guppy',growth:34,health:slots===3?100:95,hunger:slots===3?100:70,traits:[],color:'#f47f69',accent:'#ffd36e',raisedSeconds:320,origin:'ordinary',care:{bornAtMs:now-400000,lastCareAtMs:now,healthySeconds:279,nutrition:100,colourQuality:.7,meals:{flake:0,algae:0,prey:0},feedingPreference:'day',development:{resolvedStages:[],pending:[]}}};localStorage.setItem('aqualume.boutique.v1',JSON.stringify({version:1,coins:42,sales:0,kept:[],completedRunIds:[],placements:{},activeRun:{specimen:fish,x:380,y:1520,stamina:100},tankCare:{dirt:40,lastUpdatedMs:now,pellets:0}}));},slots);
await page.goto(`http://127.0.0.1:${server.address().port}`,{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Let’s begin'}).click();await page.getByRole('button',{name:'Swim',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Clean glass',exact:true}).count(),0);await page.evaluate(()=>window.testNow+=2000);await page.getByRole('button',{name:'Choose upgrades',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Choose an adaptation'});await dialog.waitFor();
const speed=dialog.getByRole('button',{name:/Swim speed/});await speed.click();assert.equal(await speed.getAttribute('aria-pressed'),'true');assert.match(await speed.textContent(),/✓/);await speed.click();assert.equal(await speed.getAttribute('aria-pressed'),'false');await speed.click();await dialog.getByRole('button',{name:/Vitality/}).click();if(slots===3)await dialog.getByRole('button',{name:/Vibrancy/}).click();
if(slots===2)await page.screenshot({path:'.superpowers/swim-upgrades-selected.png'});await dialog.getByRole('button',{name:'Confirm upgrades',exact:true}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('aqualume.boutique.v1')).activeRun.specimen.traits.length>=2);const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('aqualume.boutique.v1')).activeRun.specimen);assert.equal(saved.traits.length,slots);assert.ok(saved.traits.includes('swift')&&saved.traits.includes('vital'));assert.equal(saved.care.development.pending.length,0);assert.equal(await dialog.count(),0);await context.close();}
assert.deepEqual(errors,[]);console.log('PASS 2/3-choice stages select/deselect visibly and confirm/persist once; no Swim clean button; no page errors');
}finally{await Promise.race([browser?.close(),new Promise(r=>setTimeout(r,1500))]);server.closeAllConnections();server.close();}})().then(()=>process.exit(0),e=>{console.error(e);process.exit(1)});
