const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
(async()=>{const server=http.createServer((q,r)=>{r.setHeader('Content-Type','text/html');r.end(fs.readFileSync('dist/index.html'));});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
const args=require(process.env.CHROMIUM_ARGS_MODULE).default.args.filter(a=>a!=='--single-process');browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,args:[...args,'--disable-audio-output'],headless:true});
const page=await browser.newPage({viewport:{width:390,height:844}});page.setDefaultTimeout(20000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`,{waitUntil:'domcontentloaded'});
const welcome=page.getByRole('dialog',{name:'Welcome to SWIM.'});await welcome.waitFor();await page.getByRole('img',{name:'Rainbow tropical portrait'}).waitFor();assert.match(await welcome.textContent(),/V0.9/);assert.match(await welcome.textContent(),/nursery/);assert.match(await welcome.textContent(),/Castle bubbles/);
await page.waitForTimeout(700);await page.screenshot({path:'.superpowers/swim-welcome-390.png'});
for(const size of [{width:320,height:568},{width:844,height:390}]){await page.setViewportSize(size);await page.waitForTimeout(150);const box=await welcome.boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=size.width+1&&box.y+box.height<=size.height+1);await page.getByRole('button',{name:'Let’s begin'}).scrollIntoViewIfNeeded();}
await page.getByRole('button',{name:'Let’s begin'}).click();assert.equal(await welcome.count(),0);await page.getByRole('button',{name:'Buy fish',exact:true}).waitFor();await page.reload();await welcome.waitFor();assert.deepEqual(errors,[]);console.log('PASS welcome artwork/copy, mobile+landscape bounds, dismissal to View, welcome on next launch, no browser errors');
}finally{await Promise.race([browser?.close(),new Promise(r=>setTimeout(r,1500))]);server.closeAllConnections();server.close();}})().then(()=>process.exit(0),e=>{console.error(e);process.exit(1)});
